modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "teamlifebind"
version = "${version}"
displayName = "TeamLifeBind"
description = '''
Cross-platform team life-bind game mode.
'''

[[dependencies.teamlifebind]]
modId = "neoforge"
mandatory = true
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teamlifebind]]
modId = "minecraft"
mandatory = true
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"
